### ISSUE TITLE
Not working in symfony 3

### ISSUE THREAD

**Issue by minayaleon** [Vitre/php-console-bundle#6]
Symfony 3 no working
Fatal error: Class 'Symfony\Component\DependencyInjection\ContainerAware' not found

**Comment by axelschelfhout** [comment]
I'd like to bump this.
Error is in Vitre/PhpConsoleBundle/Console.php on line 8.
The class ContainerAware doesn't exist anymore in Symfony 3. If I find the solution I will provide it here (not spending to much time on it tho).

Any ideas on how to quick-fix this issue? Or isn't there a quick-fix?
Hope to hear from you guys soon, cuz its a great tool ;).

**Comment by Vitre** [comment]
`master` branch now only for Symfony3. 
`symfony2` branch for v2.

**Comment by axelschelfhout** [comment]
Works like a charm. Thanks!
